import "./globals.css";
import Mainheader from "@/components/mainheader";

export const metadata = {
  title: "Yum App",
  description: "Generated by Hemanth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Mainheader />
        {children}
      </body>
    </html>
  );
}
